#!/usr/bin/env bash
# configures a new Ubuntu serve to respect Holberton nginx requirements
apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html 
service nginx start
