#!/usr/bin/env bash
# configures a new Ubuntu serve to respect Holberton nginx requirements
sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start