#!/usr/bin/env bash
# configures a new Ubuntu serve to respect Holberton nginx requirements
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
