#!/usr/bin/env bash                                                                                                                        
# configures a new Ubuntu server to respect Holberton nginx requirements                                                                   

sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/#error_page 404/error_page 404/' /etc/nginx/sites-enabled/default
sudo chown -R root:ubuntu /var/www/html/
sudo touch /usr/share/nginx/html/404.html
sudo chmod -R 2775 /var/www/html/
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo chown -R root:ubuntu /usr/share/nginx/html/
sudo chmod -R 2775 /usr/share/nginx/html/
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i "/listen 80 default_server/a add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-av\
ailable/default
sudo sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n inter\
nal;}' /etc/nginx/sites-available/default
sudo service nginx start
