#!/usr/bin/env bash
#configure HAproxy

apt-get -y update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg .
cat >> /etc/haproxy/haproxy.cfg << EOF

frontend front
    bind *:80
    mode http
    default_backend back

backend back
    balance roundrobin
    server 651-web-01 34.73.136.156:80 check
    server 651-web-02 35.196.227.92:80 check
EOF
service haproxy restart
