#!/usr/bin/env bash
#configure HAproxy

sudo apt-get update
sudo apt-get -y install software-properties-common
sudo apt-get update
sudo apt-get -y install haproxy=1.5.\*
echo "ENABLE=1" | sudo tee -a /etc/default/haproxy
echo -e '\nfrontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend back\n' | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "backend backendnodes\n\tbalance roundrobin\n\tserver 864-web-01 35.196.198.246:80 check\n\tserver 864-web-02 35.231.103.98:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
