#!/usr/bin/env bash
#creates PID file
#displays "To infinity and beyond" indefinitely
#displays "I hate the kill command" during SIGTERM
#displays "Y U no love me?!" during SIGINT
#deletes PID file and terminates during SIGQUIT or SIGTERM

echo $$ >> /var/run/holbertonscript.pid

trap "echo I hate the kill command; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo Y U no love me?!; exit" SIGINT
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
