#!/usr/bin/env bash
#displays Holberton School and occurrences of luck

i=1
while [ $i -ne 11 ]; do
      if [ $i -eq 4 ]; then
	  echo "bad luck"
      elif [ $i -eq 8 ]; then
	  echo "good luck"
      else
	  echo "Holberton School"
      fi
          ((i++))
done
