#!/usr/bin/env bash
#displays Holberton School 10 times

i=1
while [ $i -ne 21 ]; do
      echo $i
      if [ $i -eq 4 ]; then
	  echo "bad luck from China"
      elif [ $i -eq 9 ]; then
	  echo "bad luck from Japan"
      elif [ $i -eq 17 ]; then
	  echo "bad luck from Italy"
      fi
          ((i++))
done
