#!/usr/bin/env bash
#configures nginx

pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i '1iuser nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/\<80\>/&80/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart